theme_dict={
    'Adolescent Health':['Adolescent "Abortion"','Adolescent "Anaemia" (WIFS)','Adolescent "Child bearing"','Adolescent Counselling','Adolescent Nutrition','AFHS Clinic','Cyber crime','Deworming','Drug abuse','Knowledge of contraceptives and early pregnancy','"Menstrual" hygiene','Adolescent Mental health','PEER Education Program','RKSK','Sex abuse','Sexual and reproductive health Education, (including myths and misconceptions','Teenage pregnancy','Tobacco and alcohol use'],
'Child Health': ['AEFI-Routine Immunization','Child Death or U5MR','Child Nutrition','Complementary feeding','Diarrhoea','Exclusive Breastfeeding','HBYC','Malnutrition','Measles rubella','NRC','Pneumonia','RBSK','Routine Immunization'],
'Communicable Diseases':['Dengue','Filaria','Hepatitis','Integrated Disease Surveillance Programme','JE/AES','Kala-Azar','Malaria','National AIDS Control Programme','National Leprosy Eradication Programme','National Programme on Containment of Anti-Microbial Resistance','National Rabies Control Programme','National Tuberculosis Elimination Programme','National Viral Hepatitis Control Program ','Programme for Prevention and Control of leptospirosis','Pulse Polio Programme','Seasonal Diseases','Typhoid','Zika Virus'],
'Health System Strengthening':['Asha Anganwadi and ANM combined meetings','Aanganwadi training','Acre gradation of doctors', 
'Acre gradation of Paramedical staff',              
'Ambulance Services',
'ANM training',
'ASHA training',
'Bio Waste Management',
'Chaos at health facility',
'District ranking',
'Doctors training'
'Equipments',
'Facility Ranking', 
'Health and wellness centres',
'Health Camps/Days',
'Infection and Prevention Management',
'Kayakalp Awards',
'Lab technician training',
'Medical negligence', 
'Medicines',
'Monitoring Visits',
'Negligence in services',
'New Government Announcements',
'New program Launch', 
'Nurse mentor training',
'OPD Services',
'Pradhan Sammelan',
'Resumption of Services',
'Service awards', 
'Strike/Protest',
'Study/Research Reports',
'Up-Gradation of health facility',
'VHSND (Village health sanitation and nutrition day)',
'Workshops/Seminars',
'Ayushman Bharat Digital Mission (ADHM)',
'Ayushman Bharat Yojana PMJAY',
'Infrastructure Related',
'Blood bank',
'PM Ayushman Bharat Health Infrastructure Mission',
'Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)'
],
'Maternal Health':['ANC Check-up',
'Anemia management',
'Birth Preparedness',
'C-Section',
'Early Registration of Pregnancy',
'FRU operationalization',
'HDU ICU for complicated delivery infertility management',
'High Risk Pregnancy',
'Child birth at home',
'Institutional child birth',
'JSSK (Janani Shishu surksha karykram)',
'Maternal Death/MMR/MDR',
'Maternal Nutrition',
'Maternity Benefits (JSY)',
'Maternity Benefits (PMMY)',
'Non Institutional Deliveries',
'PMSA Day',
'Postnatal Care'

],
'National Nutrition Program':['Integrated Child Development Services (ICDS)',
'MAA (Mothers Absolute Affection) Programme for Infant and Young Child Feeding',
'Mid-Day Meal Programme',
'National Iodine Deficiency Disorders Control Programme',
'National Iron Plus Initiative for Anaemia Control',
'National Programme for Prevention and Control of Fluorosis (NPPCF)',
'National Vitamin A prophylaxis Programme'],
'Newborn Health':['Birth Asphyxia', 
'Colostrum feeding',
'DEIC(District Early intervention center)',
'Early initiation of breastfeeding',
'First dose-BCG',
'HBNC',
'Infant Death/IMR/CDR',
'IYCF (Infant Young child feeding)',
'Kangaroo Mother Care',
'Low birth Weight',
'Navjat Shishu surakha karykram',
'NBCU',
'Newborn care corner',
'Newborn Stabilisation unit',
'newborn intensive care unit',
'Acute respiratory infection',
'Diarrhoea',
'Special Newborn Care Units',
'Still Birth'

],
"Non Communicable Diseases":["'Alzheimers' disease",
"'Anti Drug' campaign",
"Arthritis",
"Blindness",
"Cerebral palsy",
"Control Treatment of Occupational Diseases",
"Health Care for the Elderly (NPHCE)",
"Jaundice",
"Lip cleft (transfer in RBSK)",
"Mental Health Programme",
"National Oral Health programme",
"National Tobacco Control Program(NTCP)",
"NPCDCS",
"NPPCD",
"Pradhan Mantri National Dialysis Program",
"Prevention & Management of Burn Injuries (NPPMBI)",
"Sickle cell anemia"],
"Reproductive health":["Abortion",
"Condoms"
"Counselling"
"Discontinuation of service due to side effect",
"Family planning indemnity scheme",
"Fix days services",
"Injectable MPA ( Antara Program)",
"IUCD",
"Khushaal parivar diwas",
"Dampati sampark pakhwada",
"Janshankhya sthirikaran pakhwada",
"ANTARA Diwas",
"NSV Day",
"Oral contraceptive pills",
"PPIUCD and PAIUCD",
"Saas bahu beta Sammelan",
"Sterilization Female",
"Sterilization Male",
"Supply/demand FPLMIS",
"FP awareness",
"Migration",
"Myths and misconception"
],
"State Program":["ANMOL APP",
"Atal 'Swasthya' Mela", 
"'AYUSH' Programme",
"'Ayushman' Bharat (MMJAY)",
"'Balika' Samriddhi 'yojana'",
"'Child line' '1098'",
"'Kishori' Shakti 'Yojana'",
"'MANTRA' APP",
"'Mission shakti'",
"PMSBY",
"'Special ability' 'programs'",
"covid 15+ 'vaccination'",
"covid 18+ 'vaccination'", 
"covid 45+ 'vaccination'", 
"covid 60+ 'vaccination'", 
"covid 'Advisory' for Vaccination", 
"covid AEFI 'Adverse effcts'  Vaccination", 
"covid 'Appeal' for 'Vaccination'", 
"covid 'Booster Dose'",
"covid Child 'vaccination' 'infants' (under 1 years)",
"covid 'Cluster' Approach",
"covid 'Door to Door' Vaccination",
"covid 'Front line workers' vaccination", 
"covid 'Health worker' vaccination",
"covid Vaccination 'Camps'",
"covid Vaccination 'Hesitancy'",
"covid Vaccination 'Certificate'" ],
"Covid appropriate Behavior (CAB)":["Authentic Sources seeking",
"covid Avoid 'spitting'",
"covid 'touching' eyes, nose and mouth",
"covid unnecessary 'travel'",
"covid Discourage 'crowds'",
"covid 'HandWashing'",
"covid Maintain 'Distance'",
"'Mental Health' 'Covid'",  
"covid Reusable 'mask'",
"covid 'Sanitization'",
 "covid 'Cleaning'",
"covid Toll free 'helpline'",
"Violation of 'covid guideline'"],
"Stigma and Discrimination":["covid 'Appeal'",
"Corona 'survivors'",
"Corona 'warriors'"],
"Covid Other Reports":["Awareness",
"'AYUSH' Covid",
"Bio-medical waste",
"covid 'Case Detection'",
"covid 'Contact Tracing'",
"Corona 'Helpdesk'", 
"Covid 'death'",
"COVID 'facilities'",
"Covid Medication",
"covid 'Cremation'",
"covid 'Donation'",
"Covid Government 'Announcement'",
"Covid Government 'guidelines'", 
"Covid Government 'Initiatives'",
"covid'Isolation'",
"covid'Lock down'",
"'Maternal Health' in COVID",
"'Migrant labourers' issues",
"'corana' monitoring visits",  
"covid motivating report",
"corona 'new variant'",
"'Oxygen' Plants",
"'Oxygen' Supply",
"'PPE kits'",
"covid 'Quarantine'",
"covid 'Recovery rate'",
"Covid 'Research' 'Study'",
"covid 'Surveillance' Committees",
"covid 'Testing'",
"Covid 'Training'", 
"Covid 'Webinar'"]


}
language_short_name = {'aa':'Afar','ab':'Abkhazian','af':'Afrikaans','ak':'Akan','sq':'Albanian','am':'Amharic','ar':'Arabic',
'an':'Aragonese','hy':'Armenian','as':'Assamese','av':'Avaric','ae':'Avestan','ay':'Aymara','az':'Azerbaijani','ba':'Bashkir',
'bm':'Bambara','eu':'Basque','be':'Belarusian','bn':'Bengali','bh':'Bihari languages','bi':'Bislama','bo':'Tibetan','bs':'Bosnian',
'br':'Breton','bg':'Bulgarian','my':'Burmese','ca':'Catalan; Valencian','cs':'Czech','ch':'Chamorro','ce':'Chechen','zh':'Chinese',
'cu':'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic','cv':'Chuvash','kw':'Cornish','co':'Corsican',
'cr':'Cree','cy':'Welsh','cs':'Czech','da':'Danish','de':'German','dv':'Divehi; Dhivehi; Maldivian','nl':'Dutch; Flemish','dz':'Dzongkha',
'el':'Greek-Modern (1453-)','en':'English','eo':'Esperanto','et':'Estonian','eu':'Basque','ee':'Ewe','fo':'Faroese','fa':'Persian',
'fj':'Fijian','fi':'Finnish','fr':'French','fy':'Western Frisian','ff':'Fulah','Ga':'Georgian','gd':'Gaelic; Scottish Gaelic','ga':'Irish',
'gl':'Galician','gv':'Manx','el':'Greek-Modern (1453-)','gn':'Guarani','gu':'Gujarati','ht':'Haitian; Haitian Creole','ha':'Hausa',
'he':'Hebrew','hz':'Herero','hi':'Hindi','ho':'Hiri Motu','hr':'Croatian','hu':'Hungarian','hy':'Armenian','ig':'Igbo','is':'Icelandic',
'io':'Ido','ii':'Sichuan Yi; Nuosu','iu':'Inuktitut','ie':'Interlingue; Occidental',
'ia':'Interlingua (International Auxiliary Language Association)','id':'Indonesian','ik':'Inupiaq','is':'Icelandic','it':'Italian',
'jv':'Javanese','ja':'Japanese','kl':'Kalaallisut; Greenlandic','kn':'Kannada','ks':'Kashmiri','ka':'Georgian','kr':'Kanuri','kk':'Kazakh',
'km':'Central Khmer','ki':'Kikuyu; Gikuyu','rw':'Kinyarwanda','ky':'Kirghiz; Kyrgyz','kv':'Komi','kg':'Kongo','ko':'Korean',
'kj':'Kuanyama; Kwanyama','ku':'Kurdish','lo':'Lao','la':'Latin','lv':'Latvian','li':'Limburgan; Limburger; Limburgish','ln':'Lingala',
'lt':'Lithuanian','lb':'Luxembourgish; Letzeburgesch','lu':'Luba-Katanga','lg':'Ganda','mk':'Macedonian','mh':'Marshallese',
'ml':'Malayalam','mi':'Maori','mr':'Marathi','ms':'Malay','Mi':'Micmac','mk':'Macedonian','mg':'Malagasy','mt':'Maltese',
'mn':'Mongolian','mi':'Maori','ms':'Malay','my':'Burmese','na':'Nauru','nv':'Navajo; Navaho','nr':'Ndebele-South; South Ndebele',
'nd':'Ndebele-North; North Ndebele','ng':'Ndonga','ne':'Nepali','nl':'Dutch; Flemish','nn':'Norwegian Nynorsk; Nynorsk:Norwegian',
'nb':'Bokmål-Norwegian; Norwegian Bokmål','no':'Norwegian','oc':'Occitan (post 1500)','oj':'Ojibwa','or':'Oriya','om':'Oromo',
'os':'Ossetian; Ossetic','pa':'Panjabi; Punjabi','fa':'Persian','pi':'Pali','pl':'Polish','pt':'Portuguese','ps':'Pushto; Pashto',
'qu':'Quechua','rm':'Romansh','ro':'Romanian; Moldavian; Moldovan','rn':'Rundi','ru':'Russian','sg':'Sango','sa':'Sanskrit',
'si':'Sinhala; Sinhalese','sk':'Slovak','sk':'Slovak','sl':'Slovenian','se':'Northern Sami','sm':'Samoan','sn':'Shona','sd':'Sindhi',
'so':'Somali','st':'Sotho-Southern','es':'Spanish; Castilian','sq':'Albanian','sc':'Sardinian','sr':'Serbian','ss':'Swati',
'su':'Sundanese','sw':'Swahili','sv':'Swedish','ty':'Tahitian','ta':'Tamil','tt':'Tatar','te':'Telugu','tg':'Tajik','tl':'Tagalog',
'th':'Thai','bo':'Tibetan','ti':'Tigrinya','to':'Tonga (Tonga Islands)','tn':'Tswana','ts':'Tsonga','tk':'Turkmen','tr':'Turkish',
'tw':'Twi','ug':'Uighur; Uyghur','uk':'Ukrainian','ur':'Urdu','uz':'Uzbek','ve':'Venda','vi':'Vietnamese','vo':'Volapük','cy':'Welsh',
'wa':'Walloon','wo':'Wolof','xh':'Xhosa','yi':'Yiddish','yo':'Yoruba','za':'Zhuang; Chuang','zh':'Chinese','zu':'Zulu'}


theme_dict_hi={
    "Adolescent Health":["अडोलसेंट अबॉर्शन ","अडोलसेंट अनैमिया (WIFS)","अडोलसेंट चाइल्ड बेयरिंग ","अडोलसेंट कौनसेलिंग","अडोलसेंट नूट्रिशन","AFHS क्लिनिक","साइबर क्राइम ","डवोर्मिग","दृग अब्यूज़","कॉन्ट्रसेप्टिव" ,"early प्रेगनेंसी","मेन्स्ट्रुअल hygine","अडोलसेंट मैन्टल हेल्थ","PEER Education Program","RKSK","Sex abuse","Sexual and reproductive health Education, (including myths and misconceptions","Teenage pregnancy","Tobacco and alcohol use"],
"Child Health": ["AEFI-Routine Immunization","Child Death or U5MR","Child Nutrition","Complementary feeding","Diarrhoea","Exclusive Breastfeeding","HBYC","Malnutrition","Measles rubella","NRC","Pneumonia","RBSK","Routine Immunization"],
"Communicable Diseases":["Dengue","Filaria","Hepatitis","Integrated Disease Surveillance Programme","JE/AES","Kala-Azar","Malaria","National AIDS Control Programme","National Leprosy Eradication Programme","National Programme on Containment of Anti-Microbial Resistance","National Rabies Control Programme","National Tuberculosis Elimination Programme","National Viral Hepatitis Control Program ","Programme for Prevention and Control of leptospirosis","Pulse Polio Programme","Seasonal Diseases","Typhoid","Zika Virus"],
"Health System Strengthening":["Asha Anganwadi and ANM combined meetings","Aanganwadi training","Acre gradation of doctors", 
"Acre gradation of Paramedical staff",
"Ambulance Services",
"ANM training",
"ASHA training",
"Bio Waste Management",
"Chaos at health facility",
"District ranking",
"Doctors training"
"Equipment’s",
"Facility Ranking", 
"Health and wellness centres",
"Health Camps/Days",
"Infection and Prevention Management",
"Kayakalp Awards",
"Lab technician training",
"Medical negligence", 
"Medicines",
"Monitoring Visits",
"Negligence in services",
"New Government Announcements",
"New program Launch", 
"Nurse mentor training",
"OPD Services",
"Pradhan Sammelan",
"Resumption of Services",
"Service awards", 
"Strike/Protest",
"Study/Research Reports",
"Up-Gradation of health facility",
"VHSND (Village health sanitation and nutrition day)",
"Workshops/Seminars",
"Ayushman Bharat Digital Mission (ADHM)",
"Ayushman Bharat Yojana PMJAY",
"Infrastructure Related",
"Blood bank",
"PM Ayushman Bharat Health Infrastructure Mission",
"Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)"
],
"Maternal Health":["ANC Check-up",
"Anemia management",
"Birth Preparedness",
"C-Section",
"Early Registration of Pregnancy",
"FRU operationalization",
"HDU ICU for complicated delivery infertility management",
"High Risk Pregnancy",
"Child birth at home",
"Institutional child birth",
"JSSK (Janani Shishu surksha karykram)",
"Maternal Death/MMR/MDR",
"Maternal Nutrition",
"Maternity Benefits (JSY)",
"Maternity Benefits (PMMY)",
"Non Institutional Deliveries",
"PMSA Day",
"Postnatal Care"

],
"National Nutrition Program":["Integrated Child Development Services (ICDS)",
"MAA (Mothers’ Absolute Affection) Programme for Infant and Young Child Feeding",
"Mid-Day Meal Programme",
"National Iodine Deficiency Disorders Control Programme",
"National Iron Plus Initiative for Anaemia Control",
"National Programme for Prevention and Control of Fluorosis (NPPCF)",
"National Vitamin A prophylaxis Programme"],
"Newborn Health":["Birth Asphyxia", 
"Colostrum feeding",
"DEIC(District Early intervention center)",
"Early initiation of breastfeeding",
"First dose-BCG",
"HBNC",
"Infant Death/IMR/CDR",
"IYCF (Infant Young child feeding)",
"Kangaroo Mother Care",
"Low birth Weight",
"Navjat Shishu surakha karykram",
"NBCU",
"Newborn care corner",
"Newborn Stabilisation unit",
"newborn intensive care unit",
"Acute respiratory infection",
"Diarrhoea",
"Special Newborn Care Units",
"Still Birth"

],
"Non Communicable Diseases":["Alzheimer’s disease",
"Anti Drug campaign",
"Arthritis",
"Blindness",
"Cerebral palsy",
"Control Treatment of Occupational Diseases",
"Health Care for the Elderly (NPHCE)",
"Jaundice",
"Lip cleft (transfer in RBSK)",
"Mental Health Programme",
"National Oral Health programme",
"National Tobacco Control Program(NTCP)",
"NPCDCS",
"NPPCD",
"Pradhan Mantri National Dialysis Program",
"Prevention & Management of Burn Injuries (NPPMBI)",
"Sickle cell anemia"],
"Reproductive health":["Abortion",
"Condoms"
"Counselling"
"Discontinuation of service due to side effect",
"Family planning indemnity scheme",
"Fix days services",
"Injectable MPA ( Antara Program)",
"IUCD",
"Khushaal parivar diwas",
"Dampati sampark pakhwada",
"Janshankhya sthirikaran pakhwada",
"ANTARA Diwas",
"NSV Day",
"Oral contraceptive pills",
"PPIUCD and PAIUCD",
"Saas bahu beta Sammelan",
"Sterilization Female",
"Sterilization Male",
"Supply/demand FPLMIS",
"FP awareness",
"Migration",
"Myths and misconception"
],
"State Program":["ANMOL APP",
"Atal Swasthya Mela", 
"AYUSH Programme",
"Ayushman Bharat (MMJAY)",
"Balika Samriddhi yojana",
"Child line_1098",
"KSY",
"MANTRA APP",
"Mission shakti",
"SBY",
"Special ability",
"15+Vaccination",
"18+ vaccination", 
"45+ vaccination", 
"60+ vaccination", 
"Advisory for Vaccination", 
"AEFI Covid Vaccination", 
"Appeal for Vaccination", 
"Booster Dose",
"Child vaccination (under 1 years)",
"Cluster Approach",
"Door to Door Vaccination",
"Front line workers vaccination", 
"Health worker vaccination",
"Vaccination Camps",
"Vaccination Hesitancy",
"Vaccination Certificate"],
"Covid appropriate Behavior (CAB)":["Authentic Sources seeking",
"Avoid spitting",
"Avoid touching eyes, nose and mouth",
"Avoid unnecessary travel",
"Discourage crowds",
"Hand Washing",
"Maintain Distance",
"Mental Health-Covid",  
"Reusable mask",
"Sanitization/Cleaning services",
"Toll free helpline",
"Violation of guideline"],
"Stigma and Discrimination":["Appeal",
"Corona survivors",
"Corona warriors"],
"Covid Other Reports":["Awareness",
"AYUSH Covid",
"Bio-medical waste",
"Case Detection",
"Contact Tracing",
"Corona Help desk", 
"Covid death",
"COVID facilities",
"Covid Medication",
"Cremation",
"Donation",
"Covid Government Announcement",
"Covid Government guidelines", 
"Covid Government Initiatives",
"Isolation",
"Lock down",
"Maternal Health in COVID",
"Migrant labourers’ issues",
"corana Monitoring visits",  
"Motivating report",
"corona New variant",
"Oxygen Plants",
"Oxygen Supply",
"PPE kits",
"covid Quarantine",
"covid Recovery rate",
"Covid Research/Study",
"covid Surveillance Committees",
"covid Testing",
"Covid Training", 
"Covid Webinar"]
}
word_dict={'adolescent':'किशोरी',
'abortion':'गर्भपात',
'anaemia':'अनैमिया',
'Child bearing':'गर्भवती',
'Counselling':'कौनसीलिंग',
'Nutrition':'पोषण',
'clinic':'क्लिनिक',
'cyber':'साइबर',
'dworming':'डवरमिंग',
'drug':'ड्रग',
'abuse':'अब्यूज़',
'contraceptives':'गर्भ निरोधक',
'Menstrual':'माहवारी',
'sex':'यौन',
'mental health':'मानसिक स्वास्थ्य ',
'education':'सिक्षा',
'alcohol':'शराब',
'Immunization':'टीकाकरण',
'child death':'बाल मृत्यु',
'u5mr':'u5mr',
'Complementary feeding':'ऊपरी आहार',
'Diarrhoea':'डायरिया',
'Breastfeeding':'स्तनपान',
'HBYC':'HBYC',
'Malnutrition':'कुपोषण',
'Measles rubella':'मेसलेस रुबेला',
'Nutrition Rehabilitation Centre':'पोषण पुनर्वास केंद्र',
'Pneumonia':'निमोनिया',
'rashtriya bal swasthya karyakram':'राष्‍ट्रीय बाल स्‍वास्‍थ्‍य कार्यक्रम',
'Dengue':'डेंगे',
'Dengue Fever':'डेंगे फेवर',
'Filaria':'फिलरिया'   ,
'hepatitis':'हेपेटाइटिस'    ,
'Integrated Disease Surveillance Programme':'एकीकृत रोग निगरानी कार्यक्रम',
'JE':'JE',
'Japanese encephalitis':'जापानी बुखार',
'AES':'AES',
'Acute encephalitis syndrome':'अक्यूट इंसेफेलाइटिस सिंड्रोम',
'Malaria':'मलरिया',
'kalazar':'कालाजार',
'AIDS':'ऐडस',
'HIV':'एचआईवी',
'Leprosy':'कुष्ठरोग',
'anti microbial Resistance':'रोगाणुरोधी प्रतिरोध',
'Rabies':'रैबीज़',
'Tuberculosis':'ट्यूबरक्लोसिस',
'leptospirosis':'लेप्टोस्पायरोसिस',
'Polio':'पोलियो',
'Seasonal Diseases':'सीजनल रोग',
'Typhoid':'टाइफायड',
'Zika Virus':'जिका वायरस',
'Asha':'अशा' , 
'Anganwadi':'अंगनवाडि',
'ANM':'ANM',
'ambulence':'एम्बुलेंस',
'ASHA':'ASHA',


'covid':'कोविड',
'covid19':'कोविड 19',
'covid-19':'कोविड 19',

}
subthemes_lis=["Adolescent 'Abortion'",
 "Adolescent 'Anaemia' (WIFS)",
 "Adolescent 'Child bearing'",
 'Adolescent Counselling',
 'Adolescent Nutrition',
 'AFHS Clinic',
 'Cyber crime',
 'Deworming',
 'Drug abuse',
 'Knowledge of contraceptives and early pregnancy',
 "'Menstrual' hygiene",
 'Adolescent Mental health',
 'PEER Education Program',
 'RKSK',
 'Sex abuse',
 'Sexual and reproductive health Education, (including myths and misconceptions',
 'Teenage pregnancy',
 'Tobacco and alcohol use',
 'AEFI-Routine Immunization',
 'Child Death or U5MR',
 'Child Nutrition',
 'Complementary feeding',
 'Diarrhoea',
 'Exclusive Breastfeeding',
 'HBYC',
 'Malnutrition',
 'Measles rubella',
 'NRC',
 'Pneumonia',
 'RBSK',
 'Routine Immunization',
 'Dengue',
 'Filaria',
 'Hepatitis',
 'Integrated Disease Surveillance Programme',
 'JE/AES',
 'KalaAzar',
 'Malaria',
 'National AIDS Control Programme',
 'National Leprosy Eradication Programme',
 'National Programme on Containment of Anti-Microbial Resistance',
 'National Rabies Control Programme',
 'National Tuberculosis Elimination Programme',
 'National Viral Hepatitis Control Program ',
 'Programme for Prevention and Control of leptospirosis',
 'Pulse Polio Programme',
 'Seasonal Diseases',
 'Typhoid',
 'Zika Virus',
 'Asha Anganwadi and ANM combined meetings',
 'Aanganwadi training',
 'Acre gradation of doctors',
 'Acre gradation of Paramedical staff',
 'Ambulance Services',
 'ANM training',
 'ASHA training',
 'Bio Waste Management',
 'Chaos at health facility',
 'District ranking',
 'Doctors trainingEquipment’s',
 'Facility Ranking',
 'Health and wellness centres',
 'Health Camps/Days',
 'Infection and Prevention Management',
 'Kayakalp Awards',
 'Lab technician training',
 'Medical negligence',
 'Medicines',
 'Monitoring Visits',
 'Negligence in services',
 'New Government Announcements',
 'New program Launch',
 'Nurse mentor training',
 'OPD Services',
 'Pradhan Sammelan',
 'Resumption of Services',
 'Service awards',
 'Strike/Protest',
 'Study/Research Reports',
 'Up-Gradation of health facility',
 'VHSND (Village health sanitation and nutrition day)',
 'Workshops/Seminars',
 'Ayushman Bharat Digital Mission (ADHM)',
 'Ayushman Bharat Yojana PMJAY',
 'Infrastructure Related',
 'Blood bank',
 'PM Ayushman Bharat Health Infrastructure Mission',
 'Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)',
 'ANC Check-up',
 'Anemia management',
 'Birth Preparedness',
 'C-Section',
 'Early Registration of Pregnancy',
 'FRU operationalization',
 'HDU ICU for complicated delivery infertility management',
 'High Risk Pregnancy',
 'Child birth at home',
 'Institutional child birth',
 'JSSK (Janani Shishu surksha karykram)',
 'Maternal Death/MMR/MDR',
 'Maternal Nutrition',
 'Maternity Benefits (JSY)',
 'Maternity Benefits (PMMY)',
 'Non Institutional Deliveries',
 'PMSA Day',
 'Postnatal Care',
 'Integrated Child Development Services (ICDS)',
 'MAA (Mothers’ Absolute Affection) Programme for Infant and Young Child Feeding',
 'Mid-Day Meal Programme',
 'National Iodine Deficiency Disorders Control Programme',
 'National Iron Plus Initiative for Anaemia Control',
 'National Programme for Prevention and Control of Fluorosis (NPPCF)',
 'National Vitamin A prophylaxis Programme',
 'Birth Asphyxia',
 'Colostrum feeding',
 'DEIC(District Early intervention center)',
 'Early initiation of breastfeeding',
 'First dose-BCG',
 'HBNC',
 'Infant Death/IMR/CDR',
 'IYCF (Infant Young child feeding)',
 'Kangaroo Mother Care',
 'Low birth Weight',
 'Navjat Shishu surakha karykram',
 'NBCU',
 'Newborn care corner',
 'Newborn Stabilisation unit',
 'newborn intensive care unit',
 'Acute respiratory infection',
 'Diarrhoea',
 'Special Newborn Care Units',
 'Still Birth',
 "'Alzheimers' disease",
 "'Anti Drug' campaign",
 'Arthritis',
 'Blindness',
 'Cerebral palsy',
 'Control Treatment of Occupational Diseases',
 'Health Care for the Elderly (NPHCE)',
 'Jaundice',
 'Lip cleft (transfer in RBSK)',
 'Mental Health Programme',
 'National Oral Health programme',
 'National Tobacco Control Program(NTCP)',
 'NPCDCS',
 'NPPCD',
 'Pradhan Mantri National Dialysis Program',
 'Prevention & Management of Burn Injuries (NPPMBI)',
 'Sickle cell anemia',
 'Abortion',
 'CondomsCounsellingDiscontinuation of service due to side effect',
 'Family planning indemnity scheme',
 'Fix days services',
 'Injectable MPA ( Antara Program)',
 'IUCD',
 'Khushaal parivar diwas',
 'Dampati sampark pakhwada',
 'Janshankhya sthirikaran pakhwada',
 'ANTARA Diwas',
 'NSV Day',
 'Oral contraceptive pills',
 'PPIUCD and PAIUCD',
 'Saas bahu beta Sammelan',
 'Sterilization Female',
 'Sterilization Male',
 'Supply/demand FPLMIS',
 'FP awareness',
 'Migration',
 'Myths and misconception',
 'ANMOL APP',
 "Atal 'Swasthya' Mela",
 "'AYUSH' Programme",
 "'Ayushman' Bharat (MMJAY)",
 "'Balika' Samriddhi 'yojana'",
 "'Child line' '1098'",
 "'Kishori' Shakti 'Yojana'",
 "'MANTRA' APP",
 "'Mission shakti'",
 'PMSBY',
 "'Special ability' 'programs'",
 "'covid' 15+ 'vaccination'",
 "'covid' 18+ 'vaccination'",
 "'covid' 45+ 'vaccination'",
 "'covid' 60+ 'vaccination'",
 "'covid' 'Advisory' for Vaccination",
 "'covid' AEFI 'Adverse effcts'  Vaccination",
 "'covid' 'Appeal' for 'Vaccination'",
 "'covid' 'Booster Dose'",
 "'covid' Child 'vaccination' 'infants' (under 1 years)",
 "'covid' 'Cluster' Approach",
 "'covid' 'Door to Door' Vaccination",
 "'covid' 'Front line workers' vaccination",
 "'covid' 'Health worker' vaccination",
 "'covid' Vaccination 'Camps'",
 "'covid' Vaccination 'Hesitancy'",
 "'covid' Vaccination 'Certificate'",
 'Authentic Sources seeking',
 "'covid' Avoid 'spitting'",
 "'covid' 'touching' eyes, nose and mouth",
 "'covid' unnecessary 'travel'",
 "'covid' Discourage 'crowds'",
 "'covid' 'HandWashing'",
 "'covid'Maintain 'Distance'",
 "'Mental Health' 'Covid'",
 "'covid' Reusable 'mask'",
 "covid 'Sanitization'",
 "covid 'Cleaning'",
 "'covid' Toll free 'helpline'",
 "Violation of 'covid guideline'",
 "covid 'Appeal'",
 "Corona 'survivors'",
 "Corona 'warriors'",
 'Awareness',
 "'AYUSH' Covid",
 'Bio-medical waste',
 "'covid' 'Case Detection'",
 "covid 'Contact Tracing'",
 "Corona 'Helpdesk'",
 "Covid 'death'",
 "COVID 'facilities'",
 'Covid Medication',
 "covid 'Cremation'",
 "covid 'Donation'",
 "Covid Government 'Announcement'",
 "Covid Government 'guidelines'",
 "Covid Government 'Initiatives'",
 "covid'Isolation'",
 "covid'Lock down'",
 "'Maternal Health' in COVID",
 "'Migrant labourers' issues",
 "'corana' monitoring visits",
 "'covid' motivating report",
 "corona 'new variant'",
 "'Oxygen' Plants",
 "'Oxygen' Supply",
 "'PPE kits'",
 "covid 'Quarantine'",
 "covid 'Recovery rate'",
 "Covid 'Research' 'Study'",
 "covid 'Surveillance' Committees",
 "covid 'Testing'",
 "Covid 'Training'",
 "Covid 'Webinar'"]